### ISSUE TITLE
"Uncaught TypeError: window.__cmpui is not a function"

### ISSUE THREAD

**Issue by j0k3r** [vtoubiana/QookieFix#12]
Looks like it doesn't work since few days now.
It says:
> Uncaught TypeError: window.__cmpui is not a function

But the accept button has `window.__cmpui("updateConsentUi",2)` so the refuse button should work too with `window.__cmpui("setAndSaveAllConsent",!1)`

**Comment by vtoubiana** [comment]
Thanks a lot for pointing this. I just pushed the update on the chrome webstore.
Here is the link to the commit fixing this: https://github.com/vtoubiana/QookieFix/commit/b844eb62009d0e5d35c4399f77dd38022c779ba0

It was caused by "content script isolation".

**Comment by j0k3r** [comment]
Great, thanks!
