### ISSUE TITLE
Why not disconnect the observer after refuse button has been showned ?

### ISSUE THREAD

**Issue by paulgreg** [vtoubiana/QookieFix#13]
Thanks for that wonderful addon.

The MutationObserver seems always observing the document.body.
Why not call `disconnect` [1] when the refuse button has been shown to avoid unnecessary observation afterward ?

[1] https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver/disconnect

**Comment by pvgnd** [comment]
Seems to be done in 96194b0a6e155cac0757386301cc5dcae251a8c8

**Comment by paulgreg** [comment]
Thanks
