### ISSUE TITLE
Add internationalization

### ISSUE THREAD

**Issue by nymous** [vtoubiana/QookieFix#5]
Translating the string "Je refuse" in the user's language would be nice (at least fallback to English).

Should we use the browser's language, or the one from Quantcast popup (if it ever differs from the browser, I didn't test)?
First solution is bundled with WebExtensions and easy to implement, the second one would require us to detect the language used...

**Comment by vtoubiana** [comment]
I tried the first solution which seems to be working. Please let me know if it also works for you. 
By the way let me knwo hwo you'd like to have your contribution acknowledged (at this point you already wrote more code than me...).
