### ISSUE TITLE
Don't add "Je refuse" option if already displayed by site

### ISSUE THREAD

**Issue by ejmaes** [vtoubiana/QookieFix#7]
Hi!
While browsing I noticed [this](https://sourceforge.net/projects/sqlitebrowser/?source=dlp):
![qookiefix](https://user-images.githubusercontent.com/10143254/44259977-5a6d7000-a213-11e8-8176-ff26c6afdd21.PNG)
I am confused on which one to use ;)
Thanks for your work so far!

**Comment by vtoubiana** [comment]
This should be fixed by the lattest commit. I'm doing some test before updating the extension.

**Comment by vtoubiana** [comment]
The fixed has been pushed on Firefox (soon on Chrome)
